/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import ro.ghasachi.bt.persistence.tables.Exam;
import ro.ghasachi.bt.persistence.tables.Examgroup;
import ro.ghasachi.bt.persistence.tables.ExamgroupUser;
import ro.ghasachi.bt.persistence.tables.Examinstance;
import ro.ghasachi.bt.persistence.tables.Examitem;
import ro.ghasachi.bt.persistence.tables.Examitemanswer;
import ro.ghasachi.bt.persistence.tables.Foo;
import ro.ghasachi.bt.persistence.tables.Studexamanswer;
import ro.ghasachi.bt.persistence.tables.Studexaminstance;
import ro.ghasachi.bt.persistence.tables.User;
import ro.ghasachi.bt.persistence.tables.Verificationtoken;
import ro.ghasachi.bt.persistence.tables.records.ExamRecord;
import ro.ghasachi.bt.persistence.tables.records.ExamgroupRecord;
import ro.ghasachi.bt.persistence.tables.records.ExamgroupUserRecord;
import ro.ghasachi.bt.persistence.tables.records.ExaminstanceRecord;
import ro.ghasachi.bt.persistence.tables.records.ExamitemRecord;
import ro.ghasachi.bt.persistence.tables.records.ExamitemanswerRecord;
import ro.ghasachi.bt.persistence.tables.records.FooRecord;
import ro.ghasachi.bt.persistence.tables.records.StudexamanswerRecord;
import ro.ghasachi.bt.persistence.tables.records.StudexaminstanceRecord;
import ro.ghasachi.bt.persistence.tables.records.UserRecord;
import ro.ghasachi.bt.persistence.tables.records.VerificationtokenRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<FooRecord, Long> IDENTITY_FOO = Identities0.IDENTITY_FOO;
	public static final Identity<VerificationtokenRecord, Long> IDENTITY_VERIFICATIONTOKEN = Identities0.IDENTITY_VERIFICATIONTOKEN;
	public static final Identity<ExamRecord, Long> IDENTITY_EXAM = Identities0.IDENTITY_EXAM;
	public static final Identity<ExamgroupRecord, Long> IDENTITY_EXAMGROUP = Identities0.IDENTITY_EXAMGROUP;
	public static final Identity<ExaminstanceRecord, Long> IDENTITY_EXAMINSTANCE = Identities0.IDENTITY_EXAMINSTANCE;
	public static final Identity<ExamitemRecord, Long> IDENTITY_EXAMITEM = Identities0.IDENTITY_EXAMITEM;
	public static final Identity<ExamitemanswerRecord, Long> IDENTITY_EXAMITEMANSWER = Identities0.IDENTITY_EXAMITEMANSWER;
	public static final Identity<StudexamanswerRecord, Long> IDENTITY_STUDEXAMANSWER = Identities0.IDENTITY_STUDEXAMANSWER;
	public static final Identity<StudexaminstanceRecord, Long> IDENTITY_STUDEXAMINSTANCE = Identities0.IDENTITY_STUDEXAMINSTANCE;
	public static final Identity<UserRecord, Long> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<FooRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
	public static final UniqueKey<VerificationtokenRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
	public static final UniqueKey<ExamRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
	public static final UniqueKey<ExamgroupRecord> CONSTRAINT_A1 = UniqueKeys0.CONSTRAINT_A1;
	public static final UniqueKey<ExaminstanceRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
	public static final UniqueKey<ExamitemRecord> CONSTRAINT_A2 = UniqueKeys0.CONSTRAINT_A2;
	public static final UniqueKey<ExamitemanswerRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
	public static final UniqueKey<StudexamanswerRecord> CONSTRAINT_24 = UniqueKeys0.CONSTRAINT_24;
	public static final UniqueKey<StudexaminstanceRecord> CONSTRAINT_28 = UniqueKeys0.CONSTRAINT_28;
	public static final UniqueKey<UserRecord> CONSTRAINT_27 = UniqueKeys0.CONSTRAINT_27;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<VerificationtokenRecord, UserRecord> FK_NV1EIS9F8KN7U0R2PFPUJY1Y = ForeignKeys0.FK_NV1EIS9F8KN7U0R2PFPUJY1Y;
	public static final ForeignKey<ExamRecord, UserRecord> FK_A9G3SSSO96F6U0TEMYHDIE6X6 = ForeignKeys0.FK_A9G3SSSO96F6U0TEMYHDIE6X6;
	public static final ForeignKey<ExamgroupUserRecord, ExamgroupRecord> FK_DHCKVVTVGACQJ2CELIY7WE3EQ = ForeignKeys0.FK_DHCKVVTVGACQJ2CELIY7WE3EQ;
	public static final ForeignKey<ExamgroupUserRecord, UserRecord> FK_2VI353E9PXUUHRB23E1Q6ER8T = ForeignKeys0.FK_2VI353E9PXUUHRB23E1Q6ER8T;
	public static final ForeignKey<ExaminstanceRecord, ExamRecord> FK_J9CJF2LRMXOGRDG56PMLTPF6X = ForeignKeys0.FK_J9CJF2LRMXOGRDG56PMLTPF6X;
	public static final ForeignKey<ExaminstanceRecord, ExamgroupRecord> FK_K7AUB0RG88M0YSMA98OSDGXTF = ForeignKeys0.FK_K7AUB0RG88M0YSMA98OSDGXTF;
	public static final ForeignKey<ExamitemRecord, ExamRecord> FK_4F05FLQ58R5FXAASB0MD1RK4D = ForeignKeys0.FK_4F05FLQ58R5FXAASB0MD1RK4D;
	public static final ForeignKey<ExamitemanswerRecord, ExamitemRecord> FK_3PXCG18V6FWPWR9W6ALU1AW5I = ForeignKeys0.FK_3PXCG18V6FWPWR9W6ALU1AW5I;
	public static final ForeignKey<StudexamanswerRecord, ExaminstanceRecord> FK_E0CPK002DT9NL0O5JVMKQ02HO = ForeignKeys0.FK_E0CPK002DT9NL0O5JVMKQ02HO;
	public static final ForeignKey<StudexamanswerRecord, ExamitemRecord> FK_JDAMVHEKGX8LTM0PAUOBGAKW9 = ForeignKeys0.FK_JDAMVHEKGX8LTM0PAUOBGAKW9;
	public static final ForeignKey<StudexaminstanceRecord, ExaminstanceRecord> FK_TN9MIRCBFTV7XW9V7L5EHCN8P = ForeignKeys0.FK_TN9MIRCBFTV7XW9V7L5EHCN8P;
	public static final ForeignKey<StudexaminstanceRecord, UserRecord> FK_I0DRD4H77YUYYW3CUEDCDS72X = ForeignKeys0.FK_I0DRD4H77YUYYW3CUEDCDS72X;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<FooRecord, Long> IDENTITY_FOO = createIdentity(Foo.FOO, Foo.FOO.ID);
		public static Identity<VerificationtokenRecord, Long> IDENTITY_VERIFICATIONTOKEN = createIdentity(Verificationtoken.VERIFICATIONTOKEN, Verificationtoken.VERIFICATIONTOKEN.ID);
		public static Identity<ExamRecord, Long> IDENTITY_EXAM = createIdentity(Exam.EXAM, Exam.EXAM.ID);
		public static Identity<ExamgroupRecord, Long> IDENTITY_EXAMGROUP = createIdentity(Examgroup.EXAMGROUP, Examgroup.EXAMGROUP.ID);
		public static Identity<ExaminstanceRecord, Long> IDENTITY_EXAMINSTANCE = createIdentity(Examinstance.EXAMINSTANCE, Examinstance.EXAMINSTANCE.ID);
		public static Identity<ExamitemRecord, Long> IDENTITY_EXAMITEM = createIdentity(Examitem.EXAMITEM, Examitem.EXAMITEM.ID);
		public static Identity<ExamitemanswerRecord, Long> IDENTITY_EXAMITEMANSWER = createIdentity(Examitemanswer.EXAMITEMANSWER, Examitemanswer.EXAMITEMANSWER.ID);
		public static Identity<StudexamanswerRecord, Long> IDENTITY_STUDEXAMANSWER = createIdentity(Studexamanswer.STUDEXAMANSWER, Studexamanswer.STUDEXAMANSWER.ID);
		public static Identity<StudexaminstanceRecord, Long> IDENTITY_STUDEXAMINSTANCE = createIdentity(Studexaminstance.STUDEXAMINSTANCE, Studexaminstance.STUDEXAMINSTANCE.ID);
		public static Identity<UserRecord, Long> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<FooRecord> CONSTRAINT_1 = createUniqueKey(Foo.FOO, Foo.FOO.ID);
		public static final UniqueKey<VerificationtokenRecord> CONSTRAINT_A = createUniqueKey(Verificationtoken.VERIFICATIONTOKEN, Verificationtoken.VERIFICATIONTOKEN.ID);
		public static final UniqueKey<ExamRecord> CONSTRAINT_2 = createUniqueKey(Exam.EXAM, Exam.EXAM.ID);
		public static final UniqueKey<ExamgroupRecord> CONSTRAINT_A1 = createUniqueKey(Examgroup.EXAMGROUP, Examgroup.EXAMGROUP.ID);
		public static final UniqueKey<ExaminstanceRecord> CONSTRAINT_3 = createUniqueKey(Examinstance.EXAMINSTANCE, Examinstance.EXAMINSTANCE.ID);
		public static final UniqueKey<ExamitemRecord> CONSTRAINT_A2 = createUniqueKey(Examitem.EXAMITEM, Examitem.EXAMITEM.ID);
		public static final UniqueKey<ExamitemanswerRecord> CONSTRAINT_4 = createUniqueKey(Examitemanswer.EXAMITEMANSWER, Examitemanswer.EXAMITEMANSWER.ID);
		public static final UniqueKey<StudexamanswerRecord> CONSTRAINT_24 = createUniqueKey(Studexamanswer.STUDEXAMANSWER, Studexamanswer.STUDEXAMANSWER.ID);
		public static final UniqueKey<StudexaminstanceRecord> CONSTRAINT_28 = createUniqueKey(Studexaminstance.STUDEXAMINSTANCE, Studexaminstance.STUDEXAMINSTANCE.ID);
		public static final UniqueKey<UserRecord> CONSTRAINT_27 = createUniqueKey(User.USER, User.USER.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<VerificationtokenRecord, UserRecord> FK_NV1EIS9F8KN7U0R2PFPUJY1Y = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_27, Verificationtoken.VERIFICATIONTOKEN, Verificationtoken.VERIFICATIONTOKEN.USER_ID);
		public static final ForeignKey<ExamRecord, UserRecord> FK_A9G3SSSO96F6U0TEMYHDIE6X6 = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_27, Exam.EXAM, Exam.EXAM.PROFESSOR_ID);
		public static final ForeignKey<ExamgroupUserRecord, ExamgroupRecord> FK_DHCKVVTVGACQJ2CELIY7WE3EQ = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_A1, ExamgroupUser.EXAMGROUP_USER, ExamgroupUser.EXAMGROUP_USER.EXAMGROUP_ID);
		public static final ForeignKey<ExamgroupUserRecord, UserRecord> FK_2VI353E9PXUUHRB23E1Q6ER8T = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_27, ExamgroupUser.EXAMGROUP_USER, ExamgroupUser.EXAMGROUP_USER.STUDENTS_ID);
		public static final ForeignKey<ExaminstanceRecord, ExamRecord> FK_J9CJF2LRMXOGRDG56PMLTPF6X = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_2, Examinstance.EXAMINSTANCE, Examinstance.EXAMINSTANCE.EXAM_ID);
		public static final ForeignKey<ExaminstanceRecord, ExamgroupRecord> FK_K7AUB0RG88M0YSMA98OSDGXTF = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_A1, Examinstance.EXAMINSTANCE, Examinstance.EXAMINSTANCE.GROUP_ID);
		public static final ForeignKey<ExamitemRecord, ExamRecord> FK_4F05FLQ58R5FXAASB0MD1RK4D = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_2, Examitem.EXAMITEM, Examitem.EXAMITEM.EXAM_ID);
		public static final ForeignKey<ExamitemanswerRecord, ExamitemRecord> FK_3PXCG18V6FWPWR9W6ALU1AW5I = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_A2, Examitemanswer.EXAMITEMANSWER, Examitemanswer.EXAMITEMANSWER.ITEM_ID);
		public static final ForeignKey<StudexamanswerRecord, ExaminstanceRecord> FK_E0CPK002DT9NL0O5JVMKQ02HO = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_3, Studexamanswer.STUDEXAMANSWER, Studexamanswer.STUDEXAMANSWER.EXAMINSTANCE_ID);
		public static final ForeignKey<StudexamanswerRecord, ExamitemRecord> FK_JDAMVHEKGX8LTM0PAUOBGAKW9 = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_A2, Studexamanswer.STUDEXAMANSWER, Studexamanswer.STUDEXAMANSWER.ITEM_ID);
		public static final ForeignKey<StudexaminstanceRecord, ExaminstanceRecord> FK_TN9MIRCBFTV7XW9V7L5EHCN8P = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_3, Studexaminstance.STUDEXAMINSTANCE, Studexaminstance.STUDEXAMINSTANCE.EXAMINSTANCE_ID);
		public static final ForeignKey<StudexaminstanceRecord, UserRecord> FK_I0DRD4H77YUYYW3CUEDCDS72X = createForeignKey(ro.ghasachi.bt.persistence.Keys.CONSTRAINT_27, Studexaminstance.STUDEXAMINSTANCE, Studexaminstance.STUDEXAMINSTANCE.STUDENT_ID);
	}
}
