/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ro.ghasachi.bt.persistence.tables.Egroup;
import ro.ghasachi.bt.persistence.tables.Egroupuser;
import ro.ghasachi.bt.persistence.tables.Exam;
import ro.ghasachi.bt.persistence.tables.Examinstance;
import ro.ghasachi.bt.persistence.tables.Examitem;
import ro.ghasachi.bt.persistence.tables.Examitemanswer;
import ro.ghasachi.bt.persistence.tables.Studexamanswer;
import ro.ghasachi.bt.persistence.tables.Studexaminstance;
import ro.ghasachi.bt.persistence.tables.User;
import ro.ghasachi.bt.persistence.tables.Verificationtoken;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydb extends SchemaImpl {

	private static final long serialVersionUID = 2137569221;

	/**
	 * The reference instance of <code>mydb</code>
	 */
	public static final Mydb MYDB = new Mydb();

	/**
	 * No further instances allowed
	 */
	private Mydb() {
		super("mydb");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Egroup.EGROUP,
			Egroupuser.EGROUPUSER,
			Exam.EXAM,
			Examinstance.EXAMINSTANCE,
			Examitem.EXAMITEM,
			Examitemanswer.EXAMITEMANSWER,
			Studexamanswer.STUDEXAMANSWER,
			Studexaminstance.STUDEXAMINSTANCE,
			User.USER,
			Verificationtoken.VERIFICATIONTOKEN);
	}
}
