/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ro.ghasachi.bt.persistence.tables.Exam;
import ro.ghasachi.bt.persistence.tables.Examgroup;
import ro.ghasachi.bt.persistence.tables.ExamgroupUser;
import ro.ghasachi.bt.persistence.tables.Examinstance;
import ro.ghasachi.bt.persistence.tables.Examitem;
import ro.ghasachi.bt.persistence.tables.Examitemanswer;
import ro.ghasachi.bt.persistence.tables.Foo;
import ro.ghasachi.bt.persistence.tables.Studexamanswer;
import ro.ghasachi.bt.persistence.tables.Studexaminstance;
import ro.ghasachi.bt.persistence.tables.User;
import ro.ghasachi.bt.persistence.tables.Verificationtoken;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1438033811;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_023F1181_F79A_4311_B977_A61456DDD262,
			Sequences.SYSTEM_SEQUENCE_39E41150_2996_46FD_97EA_F3D758000620,
			Sequences.SYSTEM_SEQUENCE_5F55828F_0460_427E_8D56_3C444E7F8C51,
			Sequences.SYSTEM_SEQUENCE_63C750CD_E874_4344_97A0_A6A41D50203E,
			Sequences.SYSTEM_SEQUENCE_771F5E6B_6180_41A4_8850_7A6DCF71E2BC,
			Sequences.SYSTEM_SEQUENCE_BD2A4842_1C06_4A5A_ACF8_E7730D38B235,
			Sequences.SYSTEM_SEQUENCE_CAF534DA_02FA_4BC0_BA1C_4E499E495ACD,
			Sequences.SYSTEM_SEQUENCE_D6A51DF3_260C_4B7B_8632_C962B652A018,
			Sequences.SYSTEM_SEQUENCE_DAB73875_13C5_4AEC_A104_3FE77171F55B,
			Sequences.SYSTEM_SEQUENCE_E9729A93_096C_44D8_8A33_519089B035A8);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Foo.FOO,
			Verificationtoken.VERIFICATIONTOKEN,
			Exam.EXAM,
			Examgroup.EXAMGROUP,
			ExamgroupUser.EXAMGROUP_USER,
			Examinstance.EXAMINSTANCE,
			Examitem.EXAMITEM,
			Examitemanswer.EXAMITEMANSWER,
			Studexamanswer.STUDEXAMANSWER,
			Studexaminstance.STUDEXAMINSTANCE,
			User.USER);
	}
}
