/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_023F1181_F79A_4311_B977_A61456DDD262</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_023F1181_F79A_4311_B977_A61456DDD262 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_023F1181_F79A_4311_B977_A61456DDD262", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_39E41150_2996_46FD_97EA_F3D758000620</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_39E41150_2996_46FD_97EA_F3D758000620 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_39E41150_2996_46FD_97EA_F3D758000620", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_5F55828F_0460_427E_8D56_3C444E7F8C51</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_5F55828F_0460_427E_8D56_3C444E7F8C51 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_5F55828F_0460_427E_8D56_3C444E7F8C51", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_63C750CD_E874_4344_97A0_A6A41D50203E</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_63C750CD_E874_4344_97A0_A6A41D50203E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_63C750CD_E874_4344_97A0_A6A41D50203E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_771F5E6B_6180_41A4_8850_7A6DCF71E2BC</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_771F5E6B_6180_41A4_8850_7A6DCF71E2BC = new SequenceImpl<Long>("SYSTEM_SEQUENCE_771F5E6B_6180_41A4_8850_7A6DCF71E2BC", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_BD2A4842_1C06_4A5A_ACF8_E7730D38B235</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_BD2A4842_1C06_4A5A_ACF8_E7730D38B235 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_BD2A4842_1C06_4A5A_ACF8_E7730D38B235", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_CAF534DA_02FA_4BC0_BA1C_4E499E495ACD</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_CAF534DA_02FA_4BC0_BA1C_4E499E495ACD = new SequenceImpl<Long>("SYSTEM_SEQUENCE_CAF534DA_02FA_4BC0_BA1C_4E499E495ACD", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_D6A51DF3_260C_4B7B_8632_C962B652A018</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_D6A51DF3_260C_4B7B_8632_C962B652A018 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_D6A51DF3_260C_4B7B_8632_C962B652A018", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_DAB73875_13C5_4AEC_A104_3FE77171F55B</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_DAB73875_13C5_4AEC_A104_3FE77171F55B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_DAB73875_13C5_4AEC_A104_3FE77171F55B", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_E9729A93_096C_44D8_8A33_519089B035A8</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_E9729A93_096C_44D8_8A33_519089B035A8 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_E9729A93_096C_44D8_8A33_519089B035A8", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
