/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence;


import javax.annotation.Generated;

import ro.ghasachi.bt.persistence.tables.Exam;
import ro.ghasachi.bt.persistence.tables.Examgroup;
import ro.ghasachi.bt.persistence.tables.ExamgroupUser;
import ro.ghasachi.bt.persistence.tables.Examinstance;
import ro.ghasachi.bt.persistence.tables.Examitem;
import ro.ghasachi.bt.persistence.tables.Examitemanswer;
import ro.ghasachi.bt.persistence.tables.Foo;
import ro.ghasachi.bt.persistence.tables.Studexamanswer;
import ro.ghasachi.bt.persistence.tables.Studexaminstance;
import ro.ghasachi.bt.persistence.tables.User;
import ro.ghasachi.bt.persistence.tables.Verificationtoken;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.FOO
	 */
	public static final Foo FOO = ro.ghasachi.bt.persistence.tables.Foo.FOO;

	/**
	 * The table PUBLIC.VERIFICATIONTOKEN
	 */
	public static final Verificationtoken VERIFICATIONTOKEN = ro.ghasachi.bt.persistence.tables.Verificationtoken.VERIFICATIONTOKEN;

	/**
	 * The table PUBLIC.EXAM
	 */
	public static final Exam EXAM = ro.ghasachi.bt.persistence.tables.Exam.EXAM;

	/**
	 * The table PUBLIC.EXAMGROUP
	 */
	public static final Examgroup EXAMGROUP = ro.ghasachi.bt.persistence.tables.Examgroup.EXAMGROUP;

	/**
	 * The table PUBLIC.EXAMGROUP_USER
	 */
	public static final ExamgroupUser EXAMGROUP_USER = ro.ghasachi.bt.persistence.tables.ExamgroupUser.EXAMGROUP_USER;

	/**
	 * The table PUBLIC.EXAMINSTANCE
	 */
	public static final Examinstance EXAMINSTANCE = ro.ghasachi.bt.persistence.tables.Examinstance.EXAMINSTANCE;

	/**
	 * The table PUBLIC.EXAMITEM
	 */
	public static final Examitem EXAMITEM = ro.ghasachi.bt.persistence.tables.Examitem.EXAMITEM;

	/**
	 * The table PUBLIC.EXAMITEMANSWER
	 */
	public static final Examitemanswer EXAMITEMANSWER = ro.ghasachi.bt.persistence.tables.Examitemanswer.EXAMITEMANSWER;

	/**
	 * The table PUBLIC.STUDEXAMANSWER
	 */
	public static final Studexamanswer STUDEXAMANSWER = ro.ghasachi.bt.persistence.tables.Studexamanswer.STUDEXAMANSWER;

	/**
	 * The table PUBLIC.STUDEXAMINSTANCE
	 */
	public static final Studexaminstance STUDEXAMINSTANCE = ro.ghasachi.bt.persistence.tables.Studexaminstance.STUDEXAMINSTANCE;

	/**
	 * The table PUBLIC.USER
	 */
	public static final User USER = ro.ghasachi.bt.persistence.tables.User.USER;
}
