/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Egroup;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EgroupRecord extends UpdatableRecordImpl<EgroupRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = -564915922;

	/**
	 * Setter for <code>mydb.egroup.id</code>.
	 */
	public EgroupRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.egroup.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mydb.egroup.name</code>.
	 */
	public EgroupRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.egroup.name</code>.
	 */
	@Size(max = 45)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mydb.egroup.user</code>.
	 */
	public EgroupRecord setUser(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.egroup.user</code>.
	 */
	@NotNull
	public Integer getUser() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Egroup.EGROUP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Egroup.EGROUP.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Egroup.EGROUP.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EgroupRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EgroupRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EgroupRecord value3(Integer value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EgroupRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EgroupRecord
	 */
	public EgroupRecord() {
		super(Egroup.EGROUP);
	}

	/**
	 * Create a detached, initialised EgroupRecord
	 */
	public EgroupRecord(Integer id, String name, Integer user) {
		super(Egroup.EGROUP);

		setValue(0, id);
		setValue(1, name);
		setValue(2, user);
	}
}
