/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Examitemanswer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamitemanswerRecord extends UpdatableRecordImpl<ExamitemanswerRecord> implements Record4<Long, Boolean, String, Long> {

	private static final long serialVersionUID = -1463824742;

	/**
	 * Setter for <code>PUBLIC.EXAMITEMANSWER.ID</code>.
	 */
	public ExamitemanswerRecord setId(Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMITEMANSWER.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMITEMANSWER.CORRECT</code>.
	 */
	public ExamitemanswerRecord setCorrect(Boolean value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMITEMANSWER.CORRECT</code>.
	 */
	public Boolean getCorrect() {
		return (Boolean) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMITEMANSWER.VALUE</code>.
	 */
	public ExamitemanswerRecord setValue(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMITEMANSWER.VALUE</code>.
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMITEMANSWER.ITEM_ID</code>.
	 */
	public ExamitemanswerRecord setItemId(Long value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMITEMANSWER.ITEM_ID</code>.
	 */
	public Long getItemId() {
		return (Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Boolean, String, Long> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Boolean, String, Long> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Examitemanswer.EXAMITEMANSWER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field2() {
		return Examitemanswer.EXAMITEMANSWER.CORRECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Examitemanswer.EXAMITEMANSWER.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return Examitemanswer.EXAMITEMANSWER.ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value2() {
		return getCorrect();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamitemanswerRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamitemanswerRecord value2(Boolean value) {
		setCorrect(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamitemanswerRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamitemanswerRecord value4(Long value) {
		setItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamitemanswerRecord values(Long value1, Boolean value2, String value3, Long value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExamitemanswerRecord
	 */
	public ExamitemanswerRecord() {
		super(Examitemanswer.EXAMITEMANSWER);
	}

	/**
	 * Create a detached, initialised ExamitemanswerRecord
	 */
	public ExamitemanswerRecord(Long id, Boolean correct, String value, Long itemId) {
		super(Examitemanswer.EXAMITEMANSWER);

		setValue(0, id);
		setValue(1, correct);
		setValue(2, value);
		setValue(3, itemId);
	}
}
