/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ro.ghasachi.bt.persistence.tables.ExamgroupUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamgroupUserRecord extends TableRecordImpl<ExamgroupUserRecord> implements Record2<Long, Long> {

	private static final long serialVersionUID = -1167451543;

	/**
	 * Setter for <code>PUBLIC.EXAMGROUP_USER.EXAMGROUP_ID</code>.
	 */
	public ExamgroupUserRecord setExamgroupId(Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMGROUP_USER.EXAMGROUP_ID</code>.
	 */
	public Long getExamgroupId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMGROUP_USER.STUDENTS_ID</code>.
	 */
	public ExamgroupUserRecord setStudentsId(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMGROUP_USER.STUDENTS_ID</code>.
	 */
	public Long getStudentsId() {
		return (Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return ExamgroupUser.EXAMGROUP_USER.EXAMGROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return ExamgroupUser.EXAMGROUP_USER.STUDENTS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getExamgroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getStudentsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamgroupUserRecord value1(Long value) {
		setExamgroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamgroupUserRecord value2(Long value) {
		setStudentsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamgroupUserRecord values(Long value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExamgroupUserRecord
	 */
	public ExamgroupUserRecord() {
		super(ExamgroupUser.EXAMGROUP_USER);
	}

	/**
	 * Create a detached, initialised ExamgroupUserRecord
	 */
	public ExamgroupUserRecord(Long examgroupId, Long studentsId) {
		super(ExamgroupUser.EXAMGROUP_USER);

		setValue(0, examgroupId);
		setValue(1, studentsId);
	}
}
