/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Examinstance;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExaminstanceRecord extends UpdatableRecordImpl<ExaminstanceRecord> implements Record9<Integer, String, Integer, Timestamp, Timestamp, Long, Integer, Integer, Timestamp> {

	private static final long serialVersionUID = 1871627762;

	/**
	 * Setter for <code>mydb.examinstance.id</code>.
	 */
	public ExaminstanceRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mydb.examinstance.name</code>.
	 */
	public ExaminstanceRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.name</code>.
	 */
	@NotNull
	@Size(max = 45)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mydb.examinstance.status</code>.
	 */
	public ExaminstanceRecord setStatus(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.status</code>.
	 */
	public Integer getStatus() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mydb.examinstance.startdate</code>.
	 */
	public ExaminstanceRecord setStartdate(Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.startdate</code>.
	 */
	public Timestamp getStartdate() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>mydb.examinstance.enddate</code>.
	 */
	public ExaminstanceRecord setEnddate(Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.enddate</code>.
	 */
	public Timestamp getEnddate() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>mydb.examinstance.points</code>.
	 */
	public ExaminstanceRecord setPoints(Long value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.points</code>.
	 */
	public Long getPoints() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>mydb.examinstance.examid</code>.
	 */
	public ExaminstanceRecord setExamid(Integer value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.examid</code>.
	 */
	public Integer getExamid() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>mydb.examinstance.egroupid</code>.
	 */
	public ExaminstanceRecord setEgroupid(Integer value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.egroupid</code>.
	 */
	public Integer getEgroupid() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>mydb.examinstance.datecreated</code>.
	 */
	public ExaminstanceRecord setDatecreated(Timestamp value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.examinstance.datecreated</code>.
	 */
	@NotNull
	public Timestamp getDatecreated() {
		return (Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, Integer, Timestamp, Timestamp, Long, Integer, Integer, Timestamp> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, Integer, Timestamp, Timestamp, Long, Integer, Integer, Timestamp> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Examinstance.EXAMINSTANCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Examinstance.EXAMINSTANCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Examinstance.EXAMINSTANCE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Examinstance.EXAMINSTANCE.STARTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Examinstance.EXAMINSTANCE.ENDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return Examinstance.EXAMINSTANCE.POINTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Examinstance.EXAMINSTANCE.EXAMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Examinstance.EXAMINSTANCE.EGROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Examinstance.EXAMINSTANCE.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getStartdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getEnddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getPoints();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getExamid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getEgroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value3(Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value4(Timestamp value) {
		setStartdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value5(Timestamp value) {
		setEnddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value6(Long value) {
		setPoints(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value7(Integer value) {
		setExamid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value8(Integer value) {
		setEgroupid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value9(Timestamp value) {
		setDatecreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5, Long value6, Integer value7, Integer value8, Timestamp value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExaminstanceRecord
	 */
	public ExaminstanceRecord() {
		super(Examinstance.EXAMINSTANCE);
	}

	/**
	 * Create a detached, initialised ExaminstanceRecord
	 */
	public ExaminstanceRecord(Integer id, String name, Integer status, Timestamp startdate, Timestamp enddate, Long points, Integer examid, Integer egroupid, Timestamp datecreated) {
		super(Examinstance.EXAMINSTANCE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, status);
		setValue(3, startdate);
		setValue(4, enddate);
		setValue(5, points);
		setValue(6, examid);
		setValue(7, egroupid);
		setValue(8, datecreated);
	}
}
