/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Examinstance;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExaminstanceRecord extends UpdatableRecordImpl<ExaminstanceRecord> implements Record7<Long, Timestamp, String, Timestamp, Integer, Long, Long> {

	private static final long serialVersionUID = 469681536;

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.ID</code>.
	 */
	public ExaminstanceRecord setId(Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.ENDDATE</code>.
	 */
	public ExaminstanceRecord setEnddate(Timestamp value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.ENDDATE</code>.
	 */
	public Timestamp getEnddate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.NAME</code>.
	 */
	public ExaminstanceRecord setName(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.STARTDATE</code>.
	 */
	public ExaminstanceRecord setStartdate(Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.STARTDATE</code>.
	 */
	public Timestamp getStartdate() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.STATUS</code>.
	 */
	public ExaminstanceRecord setStatus(Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.STATUS</code>.
	 */
	public Integer getStatus() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.EXAM_ID</code>.
	 */
	public ExaminstanceRecord setExamId(Long value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.EXAM_ID</code>.
	 */
	public Long getExamId() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.EXAMINSTANCE.GROUP_ID</code>.
	 */
	public ExaminstanceRecord setGroupId(Long value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.EXAMINSTANCE.GROUP_ID</code>.
	 */
	public Long getGroupId() {
		return (Long) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Timestamp, String, Timestamp, Integer, Long, Long> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Timestamp, String, Timestamp, Integer, Long, Long> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Examinstance.EXAMINSTANCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Examinstance.EXAMINSTANCE.ENDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Examinstance.EXAMINSTANCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Examinstance.EXAMINSTANCE.STARTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Examinstance.EXAMINSTANCE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return Examinstance.EXAMINSTANCE.EXAM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field7() {
		return Examinstance.EXAMINSTANCE.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getEnddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getStartdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getExamId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value7() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value2(Timestamp value) {
		setEnddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value4(Timestamp value) {
		setStartdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value5(Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value6(Long value) {
		setExamId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord value7(Long value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExaminstanceRecord values(Long value1, Timestamp value2, String value3, Timestamp value4, Integer value5, Long value6, Long value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExaminstanceRecord
	 */
	public ExaminstanceRecord() {
		super(Examinstance.EXAMINSTANCE);
	}

	/**
	 * Create a detached, initialised ExaminstanceRecord
	 */
	public ExaminstanceRecord(Long id, Timestamp enddate, String name, Timestamp startdate, Integer status, Long examId, Long groupId) {
		super(Examinstance.EXAMINSTANCE);

		setValue(0, id);
		setValue(1, enddate);
		setValue(2, name);
		setValue(3, startdate);
		setValue(4, status);
		setValue(5, examId);
		setValue(6, groupId);
	}
}
