/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Studexamanswer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudexamanswerRecord extends UpdatableRecordImpl<StudexamanswerRecord> implements Record5<Integer, Integer, Integer, String, Timestamp> {

	private static final long serialVersionUID = -992012354;

	/**
	 * Setter for <code>mydb.studexamanswer.id</code>.
	 */
	public StudexamanswerRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexamanswer.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mydb.studexamanswer.studexaminst</code>.
	 */
	public StudexamanswerRecord setStudexaminst(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexamanswer.studexaminst</code>.
	 */
	@NotNull
	public Integer getStudexaminst() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>mydb.studexamanswer.examitem</code>.
	 */
	public StudexamanswerRecord setExamitem(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexamanswer.examitem</code>.
	 */
	@NotNull
	public Integer getExamitem() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mydb.studexamanswer.value</code>.
	 */
	public StudexamanswerRecord setValue(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexamanswer.value</code>.
	 */
	@NotNull
	@Size(max = 45)
	public String getValue() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mydb.studexamanswer.datecreated</code>.
	 */
	public StudexamanswerRecord setDatecreated(Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexamanswer.datecreated</code>.
	 */
	@NotNull
	public Timestamp getDatecreated() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Studexamanswer.STUDEXAMANSWER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Studexamanswer.STUDEXAMANSWER.STUDEXAMINST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Studexamanswer.STUDEXAMANSWER.EXAMITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Studexamanswer.STUDEXAMANSWER.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Studexamanswer.STUDEXAMANSWER.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStudexaminst();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getExamitem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexamanswerRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexamanswerRecord value2(Integer value) {
		setStudexaminst(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexamanswerRecord value3(Integer value) {
		setExamitem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexamanswerRecord value4(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexamanswerRecord value5(Timestamp value) {
		setDatecreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexamanswerRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudexamanswerRecord
	 */
	public StudexamanswerRecord() {
		super(Studexamanswer.STUDEXAMANSWER);
	}

	/**
	 * Create a detached, initialised StudexamanswerRecord
	 */
	public StudexamanswerRecord(Integer id, Integer studexaminst, Integer examitem, String value, Timestamp datecreated) {
		super(Studexamanswer.STUDEXAMANSWER);

		setValue(0, id);
		setValue(1, studexaminst);
		setValue(2, examitem);
		setValue(3, value);
		setValue(4, datecreated);
	}
}
