/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Studexaminstance;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudexaminstanceRecord extends UpdatableRecordImpl<StudexaminstanceRecord> implements Record3<Long, Long, Long> {

	private static final long serialVersionUID = -856793936;

	/**
	 * Setter for <code>PUBLIC.STUDEXAMINSTANCE.ID</code>.
	 */
	public StudexaminstanceRecord setId(Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.STUDEXAMINSTANCE.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.STUDEXAMINSTANCE.EXAMINSTANCE_ID</code>.
	 */
	public StudexaminstanceRecord setExaminstanceId(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.STUDEXAMINSTANCE.EXAMINSTANCE_ID</code>.
	 */
	public Long getExaminstanceId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.STUDEXAMINSTANCE.STUDENT_ID</code>.
	 */
	public StudexaminstanceRecord setStudentId(Long value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.STUDEXAMINSTANCE.STUDENT_ID</code>.
	 */
	public Long getStudentId() {
		return (Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Long> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Long> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Studexaminstance.STUDEXAMINSTANCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Studexaminstance.STUDEXAMINSTANCE.EXAMINSTANCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return Studexaminstance.STUDEXAMINSTANCE.STUDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getExaminstanceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getStudentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value2(Long value) {
		setExaminstanceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value3(Long value) {
		setStudentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord values(Long value1, Long value2, Long value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudexaminstanceRecord
	 */
	public StudexaminstanceRecord() {
		super(Studexaminstance.STUDEXAMINSTANCE);
	}

	/**
	 * Create a detached, initialised StudexaminstanceRecord
	 */
	public StudexaminstanceRecord(Long id, Long examinstanceId, Long studentId) {
		super(Studexaminstance.STUDEXAMINSTANCE);

		setValue(0, id);
		setValue(1, examinstanceId);
		setValue(2, studentId);
	}
}
