/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Studexaminstance;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudexaminstanceRecord extends UpdatableRecordImpl<StudexaminstanceRecord> implements Record6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> {

	private static final long serialVersionUID = -1466553424;

	/**
	 * Setter for <code>mydb.studexaminstance.id</code>.
	 */
	public StudexaminstanceRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexaminstance.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mydb.studexaminstance.examid</code>.
	 */
	public StudexaminstanceRecord setExamid(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexaminstance.examid</code>.
	 */
	@NotNull
	public Integer getExamid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>mydb.studexaminstance.userid</code>.
	 */
	public StudexaminstanceRecord setUserid(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexaminstance.userid</code>.
	 */
	@NotNull
	public Integer getUserid() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mydb.studexaminstance.status</code>.
	 */
	public StudexaminstanceRecord setStatus(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexaminstance.status</code>.
	 */
	@NotNull
	public Integer getStatus() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>mydb.studexaminstance.datecreated</code>.
	 */
	public StudexaminstanceRecord setDatecreated(Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexaminstance.datecreated</code>.
	 */
	@NotNull
	public Timestamp getDatecreated() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>mydb.studexaminstance.dateupdated</code>.
	 */
	public StudexaminstanceRecord setDateupdated(Timestamp value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>mydb.studexaminstance.dateupdated</code>.
	 */
	@NotNull
	public Timestamp getDateupdated() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Studexaminstance.STUDEXAMINSTANCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Studexaminstance.STUDEXAMINSTANCE.EXAMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Studexaminstance.STUDEXAMINSTANCE.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Studexaminstance.STUDEXAMINSTANCE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Studexaminstance.STUDEXAMINSTANCE.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Studexaminstance.STUDEXAMINSTANCE.DATEUPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getExamid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getDateupdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value2(Integer value) {
		setExamid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value3(Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value4(Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value5(Timestamp value) {
		setDatecreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord value6(Timestamp value) {
		setDateupdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudexaminstanceRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudexaminstanceRecord
	 */
	public StudexaminstanceRecord() {
		super(Studexaminstance.STUDEXAMINSTANCE);
	}

	/**
	 * Create a detached, initialised StudexaminstanceRecord
	 */
	public StudexaminstanceRecord(Integer id, Integer examid, Integer userid, Integer status, Timestamp datecreated, Timestamp dateupdated) {
		super(Studexaminstance.STUDEXAMINSTANCE);

		setValue(0, id);
		setValue(1, examid);
		setValue(2, userid);
		setValue(3, status);
		setValue(4, datecreated);
		setValue(5, dateupdated);
	}
}
