/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ro.ghasachi.bt.persistence.tables.Verificationtoken;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationtokenRecord extends UpdatableRecordImpl<VerificationtokenRecord> implements Record5<Long, Timestamp, String, Boolean, Long> {

	private static final long serialVersionUID = -348704914;

	/**
	 * Setter for <code>PUBLIC.VERIFICATIONTOKEN.ID</code>.
	 */
	public VerificationtokenRecord setId(Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.VERIFICATIONTOKEN.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.VERIFICATIONTOKEN.EXPIRYDATE</code>.
	 */
	public VerificationtokenRecord setExpirydate(Timestamp value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.VERIFICATIONTOKEN.EXPIRYDATE</code>.
	 */
	public Timestamp getExpirydate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.VERIFICATIONTOKEN.TOKEN</code>.
	 */
	public VerificationtokenRecord setToken(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.VERIFICATIONTOKEN.TOKEN</code>.
	 */
	public String getToken() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.VERIFICATIONTOKEN.VERIFIED</code>.
	 */
	public VerificationtokenRecord setVerified(Boolean value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.VERIFICATIONTOKEN.VERIFIED</code>.
	 */
	public Boolean getVerified() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.VERIFICATIONTOKEN.USER_ID</code>.
	 */
	public VerificationtokenRecord setUserId(Long value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.VERIFICATIONTOKEN.USER_ID</code>.
	 */
	public Long getUserId() {
		return (Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Timestamp, String, Boolean, Long> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Timestamp, String, Boolean, Long> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Verificationtoken.VERIFICATIONTOKEN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Verificationtoken.VERIFICATIONTOKEN.EXPIRYDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Verificationtoken.VERIFICATIONTOKEN.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return Verificationtoken.VERIFICATIONTOKEN.VERIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return Verificationtoken.VERIFICATIONTOKEN.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getExpirydate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getVerified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerificationtokenRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerificationtokenRecord value2(Timestamp value) {
		setExpirydate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerificationtokenRecord value3(String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerificationtokenRecord value4(Boolean value) {
		setVerified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerificationtokenRecord value5(Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VerificationtokenRecord values(Long value1, Timestamp value2, String value3, Boolean value4, Long value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VerificationtokenRecord
	 */
	public VerificationtokenRecord() {
		super(Verificationtoken.VERIFICATIONTOKEN);
	}

	/**
	 * Create a detached, initialised VerificationtokenRecord
	 */
	public VerificationtokenRecord(Long id, Timestamp expirydate, String token, Boolean verified, Long userId) {
		super(Verificationtoken.VERIFICATIONTOKEN);

		setValue(0, id);
		setValue(1, expirydate);
		setValue(2, token);
		setValue(3, verified);
		setValue(4, userId);
	}
}
