/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Mydb;
import ro.ghasachi.bt.persistence.tables.records.EgroupuserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Egroupuser extends TableImpl<EgroupuserRecord> {

	private static final long serialVersionUID = -628255075;

	/**
	 * The reference instance of <code>mydb.egroupuser</code>
	 */
	public static final Egroupuser EGROUPUSER = new Egroupuser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EgroupuserRecord> getRecordType() {
		return EgroupuserRecord.class;
	}

	/**
	 * The column <code>mydb.egroupuser.id</code>.
	 */
	public final TableField<EgroupuserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mydb.egroupuser.groupid</code>.
	 */
	public final TableField<EgroupuserRecord, Integer> GROUPID = createField("groupid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mydb.egroupuser.userid</code>.
	 */
	public final TableField<EgroupuserRecord, Integer> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>mydb.egroupuser</code> table reference
	 */
	public Egroupuser() {
		this("egroupuser", null);
	}

	/**
	 * Create an aliased <code>mydb.egroupuser</code> table reference
	 */
	public Egroupuser(String alias) {
		this(alias, EGROUPUSER);
	}

	private Egroupuser(String alias, Table<EgroupuserRecord> aliased) {
		this(alias, aliased, null);
	}

	private Egroupuser(String alias, Table<EgroupuserRecord> aliased, Field<?>[] parameters) {
		super(alias, Mydb.MYDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EgroupuserRecord, Integer> getIdentity() {
		return Keys.IDENTITY_EGROUPUSER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EgroupuserRecord> getPrimaryKey() {
		return Keys.KEY_EGROUPUSER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EgroupuserRecord>> getKeys() {
		return Arrays.<UniqueKey<EgroupuserRecord>>asList(Keys.KEY_EGROUPUSER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EgroupuserRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EgroupuserRecord, ?>>asList(Keys.GROUP_FK, Keys.USER_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Egroupuser as(String alias) {
		return new Egroupuser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Egroupuser rename(String name) {
		return new Egroupuser(name, null);
	}
}
