/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Public;
import ro.ghasachi.bt.persistence.tables.records.ExamgroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examgroup extends TableImpl<ExamgroupRecord> {

	private static final long serialVersionUID = -86887958;

	/**
	 * The reference instance of <code>PUBLIC.EXAMGROUP</code>
	 */
	public static final Examgroup EXAMGROUP = new Examgroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExamgroupRecord> getRecordType() {
		return ExamgroupRecord.class;
	}

	/**
	 * The column <code>PUBLIC.EXAMGROUP.ID</code>.
	 */
	public final TableField<ExamgroupRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.EXAMGROUP.NAME</code>.
	 */
	public final TableField<ExamgroupRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>PUBLIC.EXAMGROUP</code> table reference
	 */
	public Examgroup() {
		this("EXAMGROUP", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.EXAMGROUP</code> table reference
	 */
	public Examgroup(String alias) {
		this(alias, EXAMGROUP);
	}

	private Examgroup(String alias, Table<ExamgroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private Examgroup(String alias, Table<ExamgroupRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ExamgroupRecord, Long> getIdentity() {
		return Keys.IDENTITY_EXAMGROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ExamgroupRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_A1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ExamgroupRecord>> getKeys() {
		return Arrays.<UniqueKey<ExamgroupRecord>>asList(Keys.CONSTRAINT_A1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Examgroup as(String alias) {
		return new Examgroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Examgroup rename(String name) {
		return new Examgroup(name, null);
	}
}
