/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Public;
import ro.ghasachi.bt.persistence.tables.records.ExaminstanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examinstance extends TableImpl<ExaminstanceRecord> {

	private static final long serialVersionUID = -721443598;

	/**
	 * The reference instance of <code>PUBLIC.EXAMINSTANCE</code>
	 */
	public static final Examinstance EXAMINSTANCE = new Examinstance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExaminstanceRecord> getRecordType() {
		return ExaminstanceRecord.class;
	}

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.ID</code>.
	 */
	public final TableField<ExaminstanceRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.ENDDATE</code>.
	 */
	public final TableField<ExaminstanceRecord, Timestamp> ENDDATE = createField("ENDDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.NAME</code>.
	 */
	public final TableField<ExaminstanceRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.STARTDATE</code>.
	 */
	public final TableField<ExaminstanceRecord, Timestamp> STARTDATE = createField("STARTDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.STATUS</code>.
	 */
	public final TableField<ExaminstanceRecord, Integer> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.EXAM_ID</code>.
	 */
	public final TableField<ExaminstanceRecord, Long> EXAM_ID = createField("EXAM_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>PUBLIC.EXAMINSTANCE.GROUP_ID</code>.
	 */
	public final TableField<ExaminstanceRecord, Long> GROUP_ID = createField("GROUP_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>PUBLIC.EXAMINSTANCE</code> table reference
	 */
	public Examinstance() {
		this("EXAMINSTANCE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.EXAMINSTANCE</code> table reference
	 */
	public Examinstance(String alias) {
		this(alias, EXAMINSTANCE);
	}

	private Examinstance(String alias, Table<ExaminstanceRecord> aliased) {
		this(alias, aliased, null);
	}

	private Examinstance(String alias, Table<ExaminstanceRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ExaminstanceRecord, Long> getIdentity() {
		return Keys.IDENTITY_EXAMINSTANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ExaminstanceRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ExaminstanceRecord>> getKeys() {
		return Arrays.<UniqueKey<ExaminstanceRecord>>asList(Keys.CONSTRAINT_3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ExaminstanceRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ExaminstanceRecord, ?>>asList(Keys.FK_J9CJF2LRMXOGRDG56PMLTPF6X, Keys.FK_K7AUB0RG88M0YSMA98OSDGXTF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Examinstance as(String alias) {
		return new Examinstance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Examinstance rename(String name) {
		return new Examinstance(name, null);
	}
}
