/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Public;
import ro.ghasachi.bt.persistence.tables.records.ExamgroupUserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamgroupUser extends TableImpl<ExamgroupUserRecord> {

	private static final long serialVersionUID = 865908758;

	/**
	 * The reference instance of <code>PUBLIC.EXAMGROUP_USER</code>
	 */
	public static final ExamgroupUser EXAMGROUP_USER = new ExamgroupUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExamgroupUserRecord> getRecordType() {
		return ExamgroupUserRecord.class;
	}

	/**
	 * The column <code>PUBLIC.EXAMGROUP_USER.EXAMGROUP_ID</code>.
	 */
	public final TableField<ExamgroupUserRecord, Long> EXAMGROUP_ID = createField("EXAMGROUP_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EXAMGROUP_USER.STUDENTS_ID</code>.
	 */
	public final TableField<ExamgroupUserRecord, Long> STUDENTS_ID = createField("STUDENTS_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.EXAMGROUP_USER</code> table reference
	 */
	public ExamgroupUser() {
		this("EXAMGROUP_USER", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.EXAMGROUP_USER</code> table reference
	 */
	public ExamgroupUser(String alias) {
		this(alias, EXAMGROUP_USER);
	}

	private ExamgroupUser(String alias, Table<ExamgroupUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExamgroupUser(String alias, Table<ExamgroupUserRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ExamgroupUserRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ExamgroupUserRecord, ?>>asList(Keys.FK_DHCKVVTVGACQJ2CELIY7WE3EQ, Keys.FK_2VI353E9PXUUHRB23E1Q6ER8T);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExamgroupUser as(String alias) {
		return new ExamgroupUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ExamgroupUser rename(String name) {
		return new ExamgroupUser(name, null);
	}
}
