/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Public;
import ro.ghasachi.bt.persistence.tables.records.ExamitemRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examitem extends TableImpl<ExamitemRecord> {

	private static final long serialVersionUID = 1764784401;

	/**
	 * The reference instance of <code>PUBLIC.EXAMITEM</code>
	 */
	public static final Examitem EXAMITEM = new Examitem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExamitemRecord> getRecordType() {
		return ExamitemRecord.class;
	}

	/**
	 * The column <code>PUBLIC.EXAMITEM.ID</code>.
	 */
	public final TableField<ExamitemRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.EXAMITEM.ASSERTION</code>.
	 */
	public final TableField<ExamitemRecord, String> ASSERTION = createField("ASSERTION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.EXAMITEM.DIFICULTY</code>.
	 */
	public final TableField<ExamitemRecord, Integer> DIFICULTY = createField("DIFICULTY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EXAMITEM.POINTS</code>.
	 */
	public final TableField<ExamitemRecord, Integer> POINTS = createField("POINTS", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EXAMITEM.TYPE</code>.
	 */
	public final TableField<ExamitemRecord, Integer> TYPE = createField("TYPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EXAMITEM.EXAM_ID</code>.
	 */
	public final TableField<ExamitemRecord, Long> EXAM_ID = createField("EXAM_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>PUBLIC.EXAMITEM</code> table reference
	 */
	public Examitem() {
		this("EXAMITEM", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.EXAMITEM</code> table reference
	 */
	public Examitem(String alias) {
		this(alias, EXAMITEM);
	}

	private Examitem(String alias, Table<ExamitemRecord> aliased) {
		this(alias, aliased, null);
	}

	private Examitem(String alias, Table<ExamitemRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ExamitemRecord, Long> getIdentity() {
		return Keys.IDENTITY_EXAMITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ExamitemRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_A2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ExamitemRecord>> getKeys() {
		return Arrays.<UniqueKey<ExamitemRecord>>asList(Keys.CONSTRAINT_A2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ExamitemRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ExamitemRecord, ?>>asList(Keys.FK_4F05FLQ58R5FXAASB0MD1RK4D);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Examitem as(String alias) {
		return new Examitem(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Examitem rename(String name) {
		return new Examitem(name, null);
	}
}
