/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Public;
import ro.ghasachi.bt.persistence.tables.records.StudexaminstanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studexaminstance extends TableImpl<StudexaminstanceRecord> {

	private static final long serialVersionUID = 47555753;

	/**
	 * The reference instance of <code>PUBLIC.STUDEXAMINSTANCE</code>
	 */
	public static final Studexaminstance STUDEXAMINSTANCE = new Studexaminstance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StudexaminstanceRecord> getRecordType() {
		return StudexaminstanceRecord.class;
	}

	/**
	 * The column <code>PUBLIC.STUDEXAMINSTANCE.ID</code>.
	 */
	public final TableField<StudexaminstanceRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.STUDEXAMINSTANCE.EXAMINSTANCE_ID</code>.
	 */
	public final TableField<StudexaminstanceRecord, Long> EXAMINSTANCE_ID = createField("EXAMINSTANCE_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>PUBLIC.STUDEXAMINSTANCE.STUDENT_ID</code>.
	 */
	public final TableField<StudexaminstanceRecord, Long> STUDENT_ID = createField("STUDENT_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>PUBLIC.STUDEXAMINSTANCE</code> table reference
	 */
	public Studexaminstance() {
		this("STUDEXAMINSTANCE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.STUDEXAMINSTANCE</code> table reference
	 */
	public Studexaminstance(String alias) {
		this(alias, STUDEXAMINSTANCE);
	}

	private Studexaminstance(String alias, Table<StudexaminstanceRecord> aliased) {
		this(alias, aliased, null);
	}

	private Studexaminstance(String alias, Table<StudexaminstanceRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<StudexaminstanceRecord, Long> getIdentity() {
		return Keys.IDENTITY_STUDEXAMINSTANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StudexaminstanceRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_28;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StudexaminstanceRecord>> getKeys() {
		return Arrays.<UniqueKey<StudexaminstanceRecord>>asList(Keys.CONSTRAINT_28);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<StudexaminstanceRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<StudexaminstanceRecord, ?>>asList(Keys.FK_TN9MIRCBFTV7XW9V7L5EHCN8P, Keys.FK_I0DRD4H77YUYYW3CUEDCDS72X);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Studexaminstance as(String alias) {
		return new Studexaminstance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Studexaminstance rename(String name) {
		return new Studexaminstance(name, null);
	}
}
