/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Mydb;
import ro.ghasachi.bt.persistence.tables.records.StudexamanswerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studexamanswer extends TableImpl<StudexamanswerRecord> {

	private static final long serialVersionUID = 1756802183;

	/**
	 * The reference instance of <code>mydb.studexamanswer</code>
	 */
	public static final Studexamanswer STUDEXAMANSWER = new Studexamanswer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StudexamanswerRecord> getRecordType() {
		return StudexamanswerRecord.class;
	}

	/**
	 * The column <code>mydb.studexamanswer.id</code>.
	 */
	public final TableField<StudexamanswerRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mydb.studexamanswer.studexaminst</code>.
	 */
	public final TableField<StudexamanswerRecord, Integer> STUDEXAMINST = createField("studexaminst", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mydb.studexamanswer.examitem</code>.
	 */
	public final TableField<StudexamanswerRecord, Integer> EXAMITEM = createField("examitem", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mydb.studexamanswer.value</code>.
	 */
	public final TableField<StudexamanswerRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>mydb.studexamanswer.datecreated</code>.
	 */
	public final TableField<StudexamanswerRecord, Timestamp> DATECREATED = createField("datecreated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mydb.studexamanswer</code> table reference
	 */
	public Studexamanswer() {
		this("studexamanswer", null);
	}

	/**
	 * Create an aliased <code>mydb.studexamanswer</code> table reference
	 */
	public Studexamanswer(String alias) {
		this(alias, STUDEXAMANSWER);
	}

	private Studexamanswer(String alias, Table<StudexamanswerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Studexamanswer(String alias, Table<StudexamanswerRecord> aliased, Field<?>[] parameters) {
		super(alias, Mydb.MYDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<StudexamanswerRecord, Integer> getIdentity() {
		return Keys.IDENTITY_STUDEXAMANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StudexamanswerRecord> getPrimaryKey() {
		return Keys.KEY_STUDEXAMANSWER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StudexamanswerRecord>> getKeys() {
		return Arrays.<UniqueKey<StudexamanswerRecord>>asList(Keys.KEY_STUDEXAMANSWER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<StudexamanswerRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<StudexamanswerRecord, ?>>asList(Keys.STUDEXAMINST_FK, Keys.EXAMITEM_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Studexamanswer as(String alias) {
		return new Studexamanswer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Studexamanswer rename(String name) {
		return new Studexamanswer(name, null);
	}
}
