/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ro.ghasachi.bt.persistence.Keys;
import ro.ghasachi.bt.persistence.Public;
import ro.ghasachi.bt.persistence.tables.records.VerificationtokenRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Verificationtoken extends TableImpl<VerificationtokenRecord> {

	private static final long serialVersionUID = 696251944;

	/**
	 * The reference instance of <code>PUBLIC.VERIFICATIONTOKEN</code>
	 */
	public static final Verificationtoken VERIFICATIONTOKEN = new Verificationtoken();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VerificationtokenRecord> getRecordType() {
		return VerificationtokenRecord.class;
	}

	/**
	 * The column <code>PUBLIC.VERIFICATIONTOKEN.ID</code>.
	 */
	public final TableField<VerificationtokenRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.VERIFICATIONTOKEN.EXPIRYDATE</code>.
	 */
	public final TableField<VerificationtokenRecord, Timestamp> EXPIRYDATE = createField("EXPIRYDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.VERIFICATIONTOKEN.TOKEN</code>.
	 */
	public final TableField<VerificationtokenRecord, String> TOKEN = createField("TOKEN", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.VERIFICATIONTOKEN.VERIFIED</code>.
	 */
	public final TableField<VerificationtokenRecord, Boolean> VERIFIED = createField("VERIFIED", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>PUBLIC.VERIFICATIONTOKEN.USER_ID</code>.
	 */
	public final TableField<VerificationtokenRecord, Long> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.VERIFICATIONTOKEN</code> table reference
	 */
	public Verificationtoken() {
		this("VERIFICATIONTOKEN", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.VERIFICATIONTOKEN</code> table reference
	 */
	public Verificationtoken(String alias) {
		this(alias, VERIFICATIONTOKEN);
	}

	private Verificationtoken(String alias, Table<VerificationtokenRecord> aliased) {
		this(alias, aliased, null);
	}

	private Verificationtoken(String alias, Table<VerificationtokenRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<VerificationtokenRecord, Long> getIdentity() {
		return Keys.IDENTITY_VERIFICATIONTOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<VerificationtokenRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<VerificationtokenRecord>> getKeys() {
		return Arrays.<UniqueKey<VerificationtokenRecord>>asList(Keys.CONSTRAINT_A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<VerificationtokenRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<VerificationtokenRecord, ?>>asList(Keys.FK_NV1EIS9F8KN7U0R2PFPUJY1Y);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Verificationtoken as(String alias) {
		return new Verificationtoken(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Verificationtoken rename(String name) {
		return new Verificationtoken(name, null);
	}
}
