/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Egroupuser;
import ro.ghasachi.bt.persistence.tables.records.EgroupuserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class EgroupuserDao extends DAOImpl<EgroupuserRecord, ro.ghasachi.bt.persistence.tables.pojos.Egroupuser, Integer> {

	/**
	 * Create a new EgroupuserDao without any configuration
	 */
	public EgroupuserDao() {
		super(Egroupuser.EGROUPUSER, ro.ghasachi.bt.persistence.tables.pojos.Egroupuser.class);
	}

	/**
	 * Create a new EgroupuserDao with an attached configuration
	 */
	@Autowired
	public EgroupuserDao(Configuration configuration) {
		super(Egroupuser.EGROUPUSER, ro.ghasachi.bt.persistence.tables.pojos.Egroupuser.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ro.ghasachi.bt.persistence.tables.pojos.Egroupuser object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Egroupuser> fetchById(Integer... values) {
		return fetch(Egroupuser.EGROUPUSER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Egroupuser fetchOneById(Integer value) {
		return fetchOne(Egroupuser.EGROUPUSER.ID, value);
	}

	/**
	 * Fetch records that have <code>groupid IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Egroupuser> fetchByGroupid(Integer... values) {
		return fetch(Egroupuser.EGROUPUSER.GROUPID, values);
	}

	/**
	 * Fetch records that have <code>userid IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Egroupuser> fetchByUserid(Integer... values) {
		return fetch(Egroupuser.EGROUPUSER.USERID, values);
	}
}
