/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Examitem;
import ro.ghasachi.bt.persistence.tables.records.ExamitemRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ExamitemDao extends DAOImpl<ExamitemRecord, ro.ghasachi.bt.persistence.tables.pojos.Examitem, Integer> {

	/**
	 * Create a new ExamitemDao without any configuration
	 */
	public ExamitemDao() {
		super(Examitem.EXAMITEM, ro.ghasachi.bt.persistence.tables.pojos.Examitem.class);
	}

	/**
	 * Create a new ExamitemDao with an attached configuration
	 */
	@Autowired
	public ExamitemDao(Configuration configuration) {
		super(Examitem.EXAMITEM, ro.ghasachi.bt.persistence.tables.pojos.Examitem.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ro.ghasachi.bt.persistence.tables.pojos.Examitem object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitem> fetchById(Integer... values) {
		return fetch(Examitem.EXAMITEM.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Examitem fetchOneById(Integer value) {
		return fetchOne(Examitem.EXAMITEM.ID, value);
	}

	/**
	 * Fetch records that have <code>assertion IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitem> fetchByAssertion(String... values) {
		return fetch(Examitem.EXAMITEM.ASSERTION, values);
	}

	/**
	 * Fetch records that have <code>difficulty IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitem> fetchByDifficulty(Integer... values) {
		return fetch(Examitem.EXAMITEM.DIFFICULTY, values);
	}

	/**
	 * Fetch records that have <code>points IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitem> fetchByPoints(Long... values) {
		return fetch(Examitem.EXAMITEM.POINTS, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitem> fetchByType(Integer... values) {
		return fetch(Examitem.EXAMITEM.TYPE, values);
	}

	/**
	 * Fetch records that have <code>examid IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitem> fetchByExamid(Integer... values) {
		return fetch(Examitem.EXAMITEM.EXAMID, values);
	}
}
