/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Examinstance;
import ro.ghasachi.bt.persistence.tables.records.ExaminstanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ExaminstanceDao extends DAOImpl<ExaminstanceRecord, ro.ghasachi.bt.persistence.tables.pojos.Examinstance, Long> {

	/**
	 * Create a new ExaminstanceDao without any configuration
	 */
	public ExaminstanceDao() {
		super(Examinstance.EXAMINSTANCE, ro.ghasachi.bt.persistence.tables.pojos.Examinstance.class);
	}

	/**
	 * Create a new ExaminstanceDao with an attached configuration
	 */
	@Autowired
	public ExaminstanceDao(Configuration configuration) {
		super(Examinstance.EXAMINSTANCE, ro.ghasachi.bt.persistence.tables.pojos.Examinstance.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.Examinstance object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchById(Long... values) {
		return fetch(Examinstance.EXAMINSTANCE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Examinstance fetchOneById(Long value) {
		return fetchOne(Examinstance.EXAMINSTANCE.ID, value);
	}

	/**
	 * Fetch records that have <code>ENDDATE IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchByEnddate(Timestamp... values) {
		return fetch(Examinstance.EXAMINSTANCE.ENDDATE, values);
	}

	/**
	 * Fetch records that have <code>NAME IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchByName(String... values) {
		return fetch(Examinstance.EXAMINSTANCE.NAME, values);
	}

	/**
	 * Fetch records that have <code>STARTDATE IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchByStartdate(Timestamp... values) {
		return fetch(Examinstance.EXAMINSTANCE.STARTDATE, values);
	}

	/**
	 * Fetch records that have <code>STATUS IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchByStatus(Integer... values) {
		return fetch(Examinstance.EXAMINSTANCE.STATUS, values);
	}

	/**
	 * Fetch records that have <code>EXAM_ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchByExamId(Long... values) {
		return fetch(Examinstance.EXAMINSTANCE.EXAM_ID, values);
	}

	/**
	 * Fetch records that have <code>GROUP_ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examinstance> fetchByGroupId(Long... values) {
		return fetch(Examinstance.EXAMINSTANCE.GROUP_ID, values);
	}
}
