/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Examgroup;
import ro.ghasachi.bt.persistence.tables.records.ExamgroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ExamgroupDao extends DAOImpl<ExamgroupRecord, ro.ghasachi.bt.persistence.tables.pojos.Examgroup, Long> {

	/**
	 * Create a new ExamgroupDao without any configuration
	 */
	public ExamgroupDao() {
		super(Examgroup.EXAMGROUP, ro.ghasachi.bt.persistence.tables.pojos.Examgroup.class);
	}

	/**
	 * Create a new ExamgroupDao with an attached configuration
	 */
	@Autowired
	public ExamgroupDao(Configuration configuration) {
		super(Examgroup.EXAMGROUP, ro.ghasachi.bt.persistence.tables.pojos.Examgroup.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.Examgroup object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examgroup> fetchById(Long... values) {
		return fetch(Examgroup.EXAMGROUP.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Examgroup fetchOneById(Long value) {
		return fetchOne(Examgroup.EXAMGROUP.ID, value);
	}

	/**
	 * Fetch records that have <code>NAME IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examgroup> fetchByName(String... values) {
		return fetch(Examgroup.EXAMGROUP.NAME, values);
	}
}
