/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Exam;
import ro.ghasachi.bt.persistence.tables.records.ExamRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ExamDao extends DAOImpl<ExamRecord, ro.ghasachi.bt.persistence.tables.pojos.Exam, Long> {

	/**
	 * Create a new ExamDao without any configuration
	 */
	public ExamDao() {
		super(Exam.EXAM, ro.ghasachi.bt.persistence.tables.pojos.Exam.class);
	}

	/**
	 * Create a new ExamDao with an attached configuration
	 */
	@Autowired
	public ExamDao(Configuration configuration) {
		super(Exam.EXAM, ro.ghasachi.bt.persistence.tables.pojos.Exam.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.Exam object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchById(Long... values) {
		return fetch(Exam.EXAM.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Exam fetchOneById(Long value) {
		return fetchOne(Exam.EXAM.ID, value);
	}

	/**
	 * Fetch records that have <code>DESCRIPTION IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByDescription(String... values) {
		return fetch(Exam.EXAM.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>NAME IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByName(String... values) {
		return fetch(Exam.EXAM.NAME, values);
	}

	/**
	 * Fetch records that have <code>PROFESSOR_ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByProfessorId(Long... values) {
		return fetch(Exam.EXAM.PROFESSOR_ID, values);
	}
}
