/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Examitemanswer;
import ro.ghasachi.bt.persistence.tables.records.ExamitemanswerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ExamitemanswerDao extends DAOImpl<ExamitemanswerRecord, ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer, Long> {

	/**
	 * Create a new ExamitemanswerDao without any configuration
	 */
	public ExamitemanswerDao() {
		super(Examitemanswer.EXAMITEMANSWER, ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer.class);
	}

	/**
	 * Create a new ExamitemanswerDao with an attached configuration
	 */
	@Autowired
	public ExamitemanswerDao(Configuration configuration) {
		super(Examitemanswer.EXAMITEMANSWER, ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer> fetchById(Long... values) {
		return fetch(Examitemanswer.EXAMITEMANSWER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer fetchOneById(Long value) {
		return fetchOne(Examitemanswer.EXAMITEMANSWER.ID, value);
	}

	/**
	 * Fetch records that have <code>CORRECT IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer> fetchByCorrect(Boolean... values) {
		return fetch(Examitemanswer.EXAMITEMANSWER.CORRECT, values);
	}

	/**
	 * Fetch records that have <code>VALUE IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer> fetchByValue(String... values) {
		return fetch(Examitemanswer.EXAMITEMANSWER.VALUE, values);
	}

	/**
	 * Fetch records that have <code>ITEM_ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Examitemanswer> fetchByItemId(Long... values) {
		return fetch(Examitemanswer.EXAMITEMANSWER.ITEM_ID, values);
	}
}
