/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Exam;
import ro.ghasachi.bt.persistence.tables.records.ExamRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ExamDao extends DAOImpl<ExamRecord, ro.ghasachi.bt.persistence.tables.pojos.Exam, Integer> {

	/**
	 * Create a new ExamDao without any configuration
	 */
	public ExamDao() {
		super(Exam.EXAM, ro.ghasachi.bt.persistence.tables.pojos.Exam.class);
	}

	/**
	 * Create a new ExamDao with an attached configuration
	 */
	@Autowired
	public ExamDao(Configuration configuration) {
		super(Exam.EXAM, ro.ghasachi.bt.persistence.tables.pojos.Exam.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ro.ghasachi.bt.persistence.tables.pojos.Exam object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchById(Integer... values) {
		return fetch(Exam.EXAM.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Exam fetchOneById(Integer value) {
		return fetchOne(Exam.EXAM.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByName(String... values) {
		return fetch(Exam.EXAM.NAME, values);
	}

	/**
	 * Fetch records that have <code>userid IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByUserid(Integer... values) {
		return fetch(Exam.EXAM.USERID, values);
	}

	/**
	 * Fetch records that have <code>dificulty IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByDificulty(String... values) {
		return fetch(Exam.EXAM.DIFICULTY, values);
	}

	/**
	 * Fetch records that have <code>datecreated IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Exam> fetchByDatecreated(Timestamp... values) {
		return fetch(Exam.EXAM.DATECREATED, values);
	}
}
