/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Foo;
import ro.ghasachi.bt.persistence.tables.records.FooRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class FooDao extends DAOImpl<FooRecord, ro.ghasachi.bt.persistence.tables.pojos.Foo, Long> {

	/**
	 * Create a new FooDao without any configuration
	 */
	public FooDao() {
		super(Foo.FOO, ro.ghasachi.bt.persistence.tables.pojos.Foo.class);
	}

	/**
	 * Create a new FooDao with an attached configuration
	 */
	@Autowired
	public FooDao(Configuration configuration) {
		super(Foo.FOO, ro.ghasachi.bt.persistence.tables.pojos.Foo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.Foo object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Foo> fetchById(Long... values) {
		return fetch(Foo.FOO.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Foo fetchOneById(Long value) {
		return fetchOne(Foo.FOO.ID, value);
	}

	/**
	 * Fetch records that have <code>NAME IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Foo> fetchByName(String... values) {
		return fetch(Foo.FOO.NAME, values);
	}
}
