/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Studexaminstance;
import ro.ghasachi.bt.persistence.tables.records.StudexaminstanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class StudexaminstanceDao extends DAOImpl<StudexaminstanceRecord, ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance, Integer> {

	/**
	 * Create a new StudexaminstanceDao without any configuration
	 */
	public StudexaminstanceDao() {
		super(Studexaminstance.STUDEXAMINSTANCE, ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance.class);
	}

	/**
	 * Create a new StudexaminstanceDao with an attached configuration
	 */
	@Autowired
	public StudexaminstanceDao(Configuration configuration) {
		super(Studexaminstance.STUDEXAMINSTANCE, ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchById(Integer... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance fetchOneById(Integer value) {
		return fetchOne(Studexaminstance.STUDEXAMINSTANCE.ID, value);
	}

	/**
	 * Fetch records that have <code>examid IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByExamid(Integer... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.EXAMID, values);
	}

	/**
	 * Fetch records that have <code>userid IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByUserid(Integer... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.USERID, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByStatus(Integer... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.STATUS, values);
	}

	/**
	 * Fetch records that have <code>datecreated IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByDatecreated(Timestamp... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.DATECREATED, values);
	}

	/**
	 * Fetch records that have <code>dateupdated IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByDateupdated(Timestamp... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.DATEUPDATED, values);
	}
}
