/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.Studexaminstance;
import ro.ghasachi.bt.persistence.tables.records.StudexaminstanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class StudexaminstanceDao extends DAOImpl<StudexaminstanceRecord, ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance, Long> {

	/**
	 * Create a new StudexaminstanceDao without any configuration
	 */
	public StudexaminstanceDao() {
		super(Studexaminstance.STUDEXAMINSTANCE, ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance.class);
	}

	/**
	 * Create a new StudexaminstanceDao with an attached configuration
	 */
	@Autowired
	public StudexaminstanceDao(Configuration configuration) {
		super(Studexaminstance.STUDEXAMINSTANCE, ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchById(Long... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance fetchOneById(Long value) {
		return fetchOne(Studexaminstance.STUDEXAMINSTANCE.ID, value);
	}

	/**
	 * Fetch records that have <code>EXAMINSTANCE_ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByExaminstanceId(Long... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.EXAMINSTANCE_ID, values);
	}

	/**
	 * Fetch records that have <code>STUDENT_ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.Studexaminstance> fetchByStudentId(Long... values) {
		return fetch(Studexaminstance.STUDEXAMINSTANCE.STUDENT_ID, values);
	}
}
