/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import ro.ghasachi.bt.persistence.tables.User;
import ro.ghasachi.bt.persistence.tables.records.UserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserDao extends DAOImpl<UserRecord, ro.ghasachi.bt.persistence.tables.pojos.User, Long> {

	/**
	 * Create a new UserDao without any configuration
	 */
	public UserDao() {
		super(User.USER, ro.ghasachi.bt.persistence.tables.pojos.User.class);
	}

	/**
	 * Create a new UserDao with an attached configuration
	 */
	@Autowired
	public UserDao(Configuration configuration) {
		super(User.USER, ro.ghasachi.bt.persistence.tables.pojos.User.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(ro.ghasachi.bt.persistence.tables.pojos.User object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchById(Long... values) {
		return fetch(User.USER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public ro.ghasachi.bt.persistence.tables.pojos.User fetchOneById(Long value) {
		return fetchOne(User.USER.ID, value);
	}

	/**
	 * Fetch records that have <code>EMAIL IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchByEmail(String... values) {
		return fetch(User.USER.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>ENABLED IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchByEnabled(Boolean... values) {
		return fetch(User.USER.ENABLED, values);
	}

	/**
	 * Fetch records that have <code>LASTNAME IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchByLastname(String... values) {
		return fetch(User.USER.LASTNAME, values);
	}

	/**
	 * Fetch records that have <code>NAME IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchByName(String... values) {
		return fetch(User.USER.NAME, values);
	}

	/**
	 * Fetch records that have <code>PASSWORD IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchByPassword(String... values) {
		return fetch(User.USER.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>ROLE IN (values)</code>
	 */
	public List<ro.ghasachi.bt.persistence.tables.pojos.User> fetchByRole(String... values) {
		return fetch(User.USER.ROLE, values);
	}
}
