/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Egroup implements Serializable {

	private static final long serialVersionUID = 1554476491;

	private Integer id;
	private String  name;
	private Integer user;

	public Egroup() {}

	public Egroup(Egroup value) {
		this.id = value.id;
		this.name = value.name;
		this.user = value.user;
	}

	public Egroup(
		Integer id,
		String  name,
		Integer user
	) {
		this.id = id;
		this.name = name;
		this.user = user;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public Egroup setId(Integer id) {
		this.id = id;
		return this;
	}

	@Size(max = 45)
	public String getName() {
		return this.name;
	}

	public Egroup setName(String name) {
		this.name = name;
		return this;
	}

	@NotNull
	public Integer getUser() {
		return this.user;
	}

	public Egroup setUser(Integer user) {
		this.user = user;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Egroup (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(user);

		sb.append(")");
		return sb.toString();
	}
}
