/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamgroupUser implements Serializable {

	private static final long serialVersionUID = -1678940698;

	private Long examgroupId;
	private Long studentsId;

	public ExamgroupUser() {}

	public ExamgroupUser(ExamgroupUser value) {
		this.examgroupId = value.examgroupId;
		this.studentsId = value.studentsId;
	}

	public ExamgroupUser(
		Long examgroupId,
		Long studentsId
	) {
		this.examgroupId = examgroupId;
		this.studentsId = studentsId;
	}

	public Long getExamgroupId() {
		return this.examgroupId;
	}

	public ExamgroupUser setExamgroupId(Long examgroupId) {
		this.examgroupId = examgroupId;
		return this;
	}

	public Long getStudentsId() {
		return this.studentsId;
	}

	public ExamgroupUser setStudentsId(Long studentsId) {
		this.studentsId = studentsId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ExamgroupUser (");

		sb.append(examgroupId);
		sb.append(", ").append(studentsId);

		sb.append(")");
		return sb.toString();
	}
}
