/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examinstance implements Serializable {

	private static final long serialVersionUID = 720551683;

	private Long      id;
	private Timestamp enddate;
	private String    name;
	private Timestamp startdate;
	private Integer   status;
	private Long      examId;
	private Long      groupId;

	public Examinstance() {}

	public Examinstance(Examinstance value) {
		this.id = value.id;
		this.enddate = value.enddate;
		this.name = value.name;
		this.startdate = value.startdate;
		this.status = value.status;
		this.examId = value.examId;
		this.groupId = value.groupId;
	}

	public Examinstance(
		Long      id,
		Timestamp enddate,
		String    name,
		Timestamp startdate,
		Integer   status,
		Long      examId,
		Long      groupId
	) {
		this.id = id;
		this.enddate = enddate;
		this.name = name;
		this.startdate = startdate;
		this.status = status;
		this.examId = examId;
		this.groupId = groupId;
	}

	public Long getId() {
		return this.id;
	}

	public Examinstance setId(Long id) {
		this.id = id;
		return this;
	}

	public Timestamp getEnddate() {
		return this.enddate;
	}

	public Examinstance setEnddate(Timestamp enddate) {
		this.enddate = enddate;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public Examinstance setName(String name) {
		this.name = name;
		return this;
	}

	public Timestamp getStartdate() {
		return this.startdate;
	}

	public Examinstance setStartdate(Timestamp startdate) {
		this.startdate = startdate;
		return this;
	}

	public Integer getStatus() {
		return this.status;
	}

	public Examinstance setStatus(Integer status) {
		this.status = status;
		return this;
	}

	public Long getExamId() {
		return this.examId;
	}

	public Examinstance setExamId(Long examId) {
		this.examId = examId;
		return this;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public Examinstance setGroupId(Long groupId) {
		this.groupId = groupId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Examinstance (");

		sb.append(id);
		sb.append(", ").append(enddate);
		sb.append(", ").append(name);
		sb.append(", ").append(startdate);
		sb.append(", ").append(status);
		sb.append(", ").append(examId);
		sb.append(", ").append(groupId);

		sb.append(")");
		return sb.toString();
	}
}
