/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exam implements Serializable {

	private static final long serialVersionUID = 868818898;

	private Long   id;
	private String description;
	private String name;
	private Long   professorId;

	public Exam() {}

	public Exam(Exam value) {
		this.id = value.id;
		this.description = value.description;
		this.name = value.name;
		this.professorId = value.professorId;
	}

	public Exam(
		Long   id,
		String description,
		String name,
		Long   professorId
	) {
		this.id = id;
		this.description = description;
		this.name = name;
		this.professorId = professorId;
	}

	public Long getId() {
		return this.id;
	}

	public Exam setId(Long id) {
		this.id = id;
		return this;
	}

	public String getDescription() {
		return this.description;
	}

	public Exam setDescription(String description) {
		this.description = description;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public Exam setName(String name) {
		this.name = name;
		return this;
	}

	public Long getProfessorId() {
		return this.professorId;
	}

	public Exam setProfessorId(Long professorId) {
		this.professorId = professorId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Exam (");

		sb.append(id);
		sb.append(", ").append(description);
		sb.append(", ").append(name);
		sb.append(", ").append(professorId);

		sb.append(")");
		return sb.toString();
	}
}
