/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examgroup implements Serializable {

	private static final long serialVersionUID = -331281540;

	private Long   id;
	private String name;

	public Examgroup() {}

	public Examgroup(Examgroup value) {
		this.id = value.id;
		this.name = value.name;
	}

	public Examgroup(
		Long   id,
		String name
	) {
		this.id = id;
		this.name = name;
	}

	public Long getId() {
		return this.id;
	}

	public Examgroup setId(Long id) {
		this.id = id;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public Examgroup setName(String name) {
		this.name = name;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Examgroup (");

		sb.append(id);
		sb.append(", ").append(name);

		sb.append(")");
		return sb.toString();
	}
}
