/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examitemanswer implements Serializable {

	private static final long serialVersionUID = -851604776;

	private Integer id;
	private Byte    correct;
	private String  value;
	private Integer itemid;

	public Examitemanswer() {}

	public Examitemanswer(Examitemanswer value) {
		this.id = value.id;
		this.correct = value.correct;
		this.value = value.value;
		this.itemid = value.itemid;
	}

	public Examitemanswer(
		Integer id,
		Byte    correct,
		String  value,
		Integer itemid
	) {
		this.id = id;
		this.correct = correct;
		this.value = value;
		this.itemid = itemid;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public Examitemanswer setId(Integer id) {
		this.id = id;
		return this;
	}

	@NotNull
	public Byte getCorrect() {
		return this.correct;
	}

	public Examitemanswer setCorrect(Byte correct) {
		this.correct = correct;
		return this;
	}

	@NotNull
	@Size(max = 100)
	public String getValue() {
		return this.value;
	}

	public Examitemanswer setValue(String value) {
		this.value = value;
		return this;
	}

	@NotNull
	public Integer getItemid() {
		return this.itemid;
	}

	public Examitemanswer setItemid(Integer itemid) {
		this.itemid = itemid;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Examitemanswer (");

		sb.append(id);
		sb.append(", ").append(correct);
		sb.append(", ").append(value);
		sb.append(", ").append(itemid);

		sb.append(")");
		return sb.toString();
	}
}
