/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examitemanswer implements Serializable {

	private static final long serialVersionUID = -2054842482;

	private Long    id;
	private Boolean correct;
	private String  value;
	private Long    itemId;

	public Examitemanswer() {}

	public Examitemanswer(Examitemanswer value) {
		this.id = value.id;
		this.correct = value.correct;
		this.value = value.value;
		this.itemId = value.itemId;
	}

	public Examitemanswer(
		Long    id,
		Boolean correct,
		String  value,
		Long    itemId
	) {
		this.id = id;
		this.correct = correct;
		this.value = value;
		this.itemId = itemId;
	}

	public Long getId() {
		return this.id;
	}

	public Examitemanswer setId(Long id) {
		this.id = id;
		return this;
	}

	public Boolean getCorrect() {
		return this.correct;
	}

	public Examitemanswer setCorrect(Boolean correct) {
		this.correct = correct;
		return this;
	}

	public String getValue() {
		return this.value;
	}

	public Examitemanswer setValue(String value) {
		this.value = value;
		return this;
	}

	public Long getItemId() {
		return this.itemId;
	}

	public Examitemanswer setItemId(Long itemId) {
		this.itemId = itemId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Examitemanswer (");

		sb.append(id);
		sb.append(", ").append(correct);
		sb.append(", ").append(value);
		sb.append(", ").append(itemId);

		sb.append(")");
		return sb.toString();
	}
}
