/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examitem implements Serializable {

	private static final long serialVersionUID = 860022044;

	private Integer id;
	private String  assertion;
	private Integer difficulty;
	private Long    points;
	private Integer type;
	private Integer examid;

	public Examitem() {}

	public Examitem(Examitem value) {
		this.id = value.id;
		this.assertion = value.assertion;
		this.difficulty = value.difficulty;
		this.points = value.points;
		this.type = value.type;
		this.examid = value.examid;
	}

	public Examitem(
		Integer id,
		String  assertion,
		Integer difficulty,
		Long    points,
		Integer type,
		Integer examid
	) {
		this.id = id;
		this.assertion = assertion;
		this.difficulty = difficulty;
		this.points = points;
		this.type = type;
		this.examid = examid;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public Examitem setId(Integer id) {
		this.id = id;
		return this;
	}

	@NotNull
	@Size(max = 200)
	public String getAssertion() {
		return this.assertion;
	}

	public Examitem setAssertion(String assertion) {
		this.assertion = assertion;
		return this;
	}

	public Integer getDifficulty() {
		return this.difficulty;
	}

	public Examitem setDifficulty(Integer difficulty) {
		this.difficulty = difficulty;
		return this;
	}

	public Long getPoints() {
		return this.points;
	}

	public Examitem setPoints(Long points) {
		this.points = points;
		return this;
	}

	public Integer getType() {
		return this.type;
	}

	public Examitem setType(Integer type) {
		this.type = type;
		return this;
	}

	public Integer getExamid() {
		return this.examid;
	}

	public Examitem setExamid(Integer examid) {
		this.examid = examid;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Examitem (");

		sb.append(id);
		sb.append(", ").append(assertion);
		sb.append(", ").append(difficulty);
		sb.append(", ").append(points);
		sb.append(", ").append(type);
		sb.append(", ").append(examid);

		sb.append(")");
		return sb.toString();
	}
}
