/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studexaminstance implements Serializable {

	private static final long serialVersionUID = 1046299813;

	private Integer   id;
	private Integer   examid;
	private Integer   userid;
	private Integer   status;
	private Timestamp datecreated;
	private Timestamp dateupdated;

	public Studexaminstance() {}

	public Studexaminstance(Studexaminstance value) {
		this.id = value.id;
		this.examid = value.examid;
		this.userid = value.userid;
		this.status = value.status;
		this.datecreated = value.datecreated;
		this.dateupdated = value.dateupdated;
	}

	public Studexaminstance(
		Integer   id,
		Integer   examid,
		Integer   userid,
		Integer   status,
		Timestamp datecreated,
		Timestamp dateupdated
	) {
		this.id = id;
		this.examid = examid;
		this.userid = userid;
		this.status = status;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public Studexaminstance setId(Integer id) {
		this.id = id;
		return this;
	}

	@NotNull
	public Integer getExamid() {
		return this.examid;
	}

	public Studexaminstance setExamid(Integer examid) {
		this.examid = examid;
		return this;
	}

	@NotNull
	public Integer getUserid() {
		return this.userid;
	}

	public Studexaminstance setUserid(Integer userid) {
		this.userid = userid;
		return this;
	}

	@NotNull
	public Integer getStatus() {
		return this.status;
	}

	public Studexaminstance setStatus(Integer status) {
		this.status = status;
		return this;
	}

	@NotNull
	public Timestamp getDatecreated() {
		return this.datecreated;
	}

	public Studexaminstance setDatecreated(Timestamp datecreated) {
		this.datecreated = datecreated;
		return this;
	}

	@NotNull
	public Timestamp getDateupdated() {
		return this.dateupdated;
	}

	public Studexaminstance setDateupdated(Timestamp dateupdated) {
		this.dateupdated = dateupdated;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Studexaminstance (");

		sb.append(id);
		sb.append(", ").append(examid);
		sb.append(", ").append(userid);
		sb.append(", ").append(status);
		sb.append(", ").append(datecreated);
		sb.append(", ").append(dateupdated);

		sb.append(")");
		return sb.toString();
	}
}
