/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studexamanswer implements Serializable {

	private static final long serialVersionUID = 516470449;

	private Integer   id;
	private Integer   studexaminst;
	private Integer   examitem;
	private String    value;
	private Timestamp datecreated;

	public Studexamanswer() {}

	public Studexamanswer(Studexamanswer value) {
		this.id = value.id;
		this.studexaminst = value.studexaminst;
		this.examitem = value.examitem;
		this.value = value.value;
		this.datecreated = value.datecreated;
	}

	public Studexamanswer(
		Integer   id,
		Integer   studexaminst,
		Integer   examitem,
		String    value,
		Timestamp datecreated
	) {
		this.id = id;
		this.studexaminst = studexaminst;
		this.examitem = examitem;
		this.value = value;
		this.datecreated = datecreated;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public Studexamanswer setId(Integer id) {
		this.id = id;
		return this;
	}

	@NotNull
	public Integer getStudexaminst() {
		return this.studexaminst;
	}

	public Studexamanswer setStudexaminst(Integer studexaminst) {
		this.studexaminst = studexaminst;
		return this;
	}

	@NotNull
	public Integer getExamitem() {
		return this.examitem;
	}

	public Studexamanswer setExamitem(Integer examitem) {
		this.examitem = examitem;
		return this;
	}

	@NotNull
	@Size(max = 45)
	public String getValue() {
		return this.value;
	}

	public Studexamanswer setValue(String value) {
		this.value = value;
		return this;
	}

	@NotNull
	public Timestamp getDatecreated() {
		return this.datecreated;
	}

	public Studexamanswer setDatecreated(Timestamp datecreated) {
		this.datecreated = datecreated;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Studexamanswer (");

		sb.append(id);
		sb.append(", ").append(studexaminst);
		sb.append(", ").append(examitem);
		sb.append(", ").append(value);
		sb.append(", ").append(datecreated);

		sb.append(")");
		return sb.toString();
	}
}
