/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studexamanswer implements Serializable {

	private static final long serialVersionUID = 720920727;

	private Long   id;
	private String value;
	private Long   examinstanceId;
	private Long   itemId;

	public Studexamanswer() {}

	public Studexamanswer(Studexamanswer value) {
		this.id = value.id;
		this.value = value.value;
		this.examinstanceId = value.examinstanceId;
		this.itemId = value.itemId;
	}

	public Studexamanswer(
		Long   id,
		String value,
		Long   examinstanceId,
		Long   itemId
	) {
		this.id = id;
		this.value = value;
		this.examinstanceId = examinstanceId;
		this.itemId = itemId;
	}

	public Long getId() {
		return this.id;
	}

	public Studexamanswer setId(Long id) {
		this.id = id;
		return this;
	}

	public String getValue() {
		return this.value;
	}

	public Studexamanswer setValue(String value) {
		this.value = value;
		return this;
	}

	public Long getExaminstanceId() {
		return this.examinstanceId;
	}

	public Studexamanswer setExaminstanceId(Long examinstanceId) {
		this.examinstanceId = examinstanceId;
		return this;
	}

	public Long getItemId() {
		return this.itemId;
	}

	public Studexamanswer setItemId(Long itemId) {
		this.itemId = itemId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Studexamanswer (");

		sb.append(id);
		sb.append(", ").append(value);
		sb.append(", ").append(examinstanceId);
		sb.append(", ").append(itemId);

		sb.append(")");
		return sb.toString();
	}
}
