/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studexaminstance implements Serializable {

	private static final long serialVersionUID = -737020624;

	private Long id;
	private Long examinstanceId;
	private Long studentId;

	public Studexaminstance() {}

	public Studexaminstance(Studexaminstance value) {
		this.id = value.id;
		this.examinstanceId = value.examinstanceId;
		this.studentId = value.studentId;
	}

	public Studexaminstance(
		Long id,
		Long examinstanceId,
		Long studentId
	) {
		this.id = id;
		this.examinstanceId = examinstanceId;
		this.studentId = studentId;
	}

	public Long getId() {
		return this.id;
	}

	public Studexaminstance setId(Long id) {
		this.id = id;
		return this;
	}

	public Long getExaminstanceId() {
		return this.examinstanceId;
	}

	public Studexaminstance setExaminstanceId(Long examinstanceId) {
		this.examinstanceId = examinstanceId;
		return this;
	}

	public Long getStudentId() {
		return this.studentId;
	}

	public Studexaminstance setStudentId(Long studentId) {
		this.studentId = studentId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Studexaminstance (");

		sb.append(id);
		sb.append(", ").append(examinstanceId);
		sb.append(", ").append(studentId);

		sb.append(")");
		return sb.toString();
	}
}
