/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

	private static final long serialVersionUID = -1338856344;

	private Integer   id;
	private String    email;
	private String    name;
	private String    lastname;
	private String    password;
	private Byte      enabled;
	private String    role;
	private Timestamp datecreated;

	public User() {}

	public User(User value) {
		this.id = value.id;
		this.email = value.email;
		this.name = value.name;
		this.lastname = value.lastname;
		this.password = value.password;
		this.enabled = value.enabled;
		this.role = value.role;
		this.datecreated = value.datecreated;
	}

	public User(
		Integer   id,
		String    email,
		String    name,
		String    lastname,
		String    password,
		Byte      enabled,
		String    role,
		Timestamp datecreated
	) {
		this.id = id;
		this.email = email;
		this.name = name;
		this.lastname = lastname;
		this.password = password;
		this.enabled = enabled;
		this.role = role;
		this.datecreated = datecreated;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public User setId(Integer id) {
		this.id = id;
		return this;
	}

	@NotNull
	@Size(max = 45)
	public String getEmail() {
		return this.email;
	}

	public User setEmail(String email) {
		this.email = email;
		return this;
	}

	@NotNull
	@Size(max = 45)
	public String getName() {
		return this.name;
	}

	public User setName(String name) {
		this.name = name;
		return this;
	}

	@NotNull
	@Size(max = 45)
	public String getLastname() {
		return this.lastname;
	}

	public User setLastname(String lastname) {
		this.lastname = lastname;
		return this;
	}

	@Size(max = 45)
	public String getPassword() {
		return this.password;
	}

	public User setPassword(String password) {
		this.password = password;
		return this;
	}

	@NotNull
	public Byte getEnabled() {
		return this.enabled;
	}

	public User setEnabled(Byte enabled) {
		this.enabled = enabled;
		return this;
	}

	@NotNull
	@Size(max = 45)
	public String getRole() {
		return this.role;
	}

	public User setRole(String role) {
		this.role = role;
		return this;
	}

	@NotNull
	public Timestamp getDatecreated() {
		return this.datecreated;
	}

	public User setDatecreated(Timestamp datecreated) {
		this.datecreated = datecreated;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("User (");

		sb.append(id);
		sb.append(", ").append(email);
		sb.append(", ").append(name);
		sb.append(", ").append(lastname);
		sb.append(", ").append(password);
		sb.append(", ").append(enabled);
		sb.append(", ").append(role);
		sb.append(", ").append(datecreated);

		sb.append(")");
		return sb.toString();
	}
}
