/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

	private static final long serialVersionUID = -397493550;

	private Long    id;
	private String  email;
	private Boolean enabled;
	private String  lastname;
	private String  name;
	private String  password;
	private String  role;

	public User() {}

	public User(User value) {
		this.id = value.id;
		this.email = value.email;
		this.enabled = value.enabled;
		this.lastname = value.lastname;
		this.name = value.name;
		this.password = value.password;
		this.role = value.role;
	}

	public User(
		Long    id,
		String  email,
		Boolean enabled,
		String  lastname,
		String  name,
		String  password,
		String  role
	) {
		this.id = id;
		this.email = email;
		this.enabled = enabled;
		this.lastname = lastname;
		this.name = name;
		this.password = password;
		this.role = role;
	}

	public Long getId() {
		return this.id;
	}

	public User setId(Long id) {
		this.id = id;
		return this;
	}

	public String getEmail() {
		return this.email;
	}

	public User setEmail(String email) {
		this.email = email;
		return this;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public User setEnabled(Boolean enabled) {
		this.enabled = enabled;
		return this;
	}

	public String getLastname() {
		return this.lastname;
	}

	public User setLastname(String lastname) {
		this.lastname = lastname;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public User setName(String name) {
		this.name = name;
		return this;
	}

	public String getPassword() {
		return this.password;
	}

	public User setPassword(String password) {
		this.password = password;
		return this;
	}

	public String getRole() {
		return this.role;
	}

	public User setRole(String role) {
		this.role = role;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("User (");

		sb.append(id);
		sb.append(", ").append(email);
		sb.append(", ").append(enabled);
		sb.append(", ").append(lastname);
		sb.append(", ").append(name);
		sb.append(", ").append(password);
		sb.append(", ").append(role);

		sb.append(")");
		return sb.toString();
	}
}
