/**
 * This class is generated by jOOQ
 */
package ro.ghasachi.bt.persistence.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Verificationtoken implements Serializable {

	private static final long serialVersionUID = -81727619;

	private Long      id;
	private Timestamp expirydate;
	private String    token;
	private Boolean   verified;
	private Long      userId;

	public Verificationtoken() {}

	public Verificationtoken(Verificationtoken value) {
		this.id = value.id;
		this.expirydate = value.expirydate;
		this.token = value.token;
		this.verified = value.verified;
		this.userId = value.userId;
	}

	public Verificationtoken(
		Long      id,
		Timestamp expirydate,
		String    token,
		Boolean   verified,
		Long      userId
	) {
		this.id = id;
		this.expirydate = expirydate;
		this.token = token;
		this.verified = verified;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public Verificationtoken setId(Long id) {
		this.id = id;
		return this;
	}

	public Timestamp getExpirydate() {
		return this.expirydate;
	}

	public Verificationtoken setExpirydate(Timestamp expirydate) {
		this.expirydate = expirydate;
		return this;
	}

	public String getToken() {
		return this.token;
	}

	public Verificationtoken setToken(String token) {
		this.token = token;
		return this;
	}

	public Boolean getVerified() {
		return this.verified;
	}

	public Verificationtoken setVerified(Boolean verified) {
		this.verified = verified;
		return this;
	}

	public Long getUserId() {
		return this.userId;
	}

	public Verificationtoken setUserId(Long userId) {
		this.userId = userId;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Verificationtoken (");

		sb.append(id);
		sb.append(", ").append(expirydate);
		sb.append(", ").append(token);
		sb.append(", ").append(verified);
		sb.append(", ").append(userId);

		sb.append(")");
		return sb.toString();
	}
}
